### ISSUE TITLE
Regex for path['name'] in dbt_project.yml is being read incorrectly in Cloud Composer GCP

### ISSUE THREAD

**Issue by khaledalarja** [fishtown-analytics/docs.getdbt.com#571]
## Steps to reproduce:
This is a case for dbt installed on Cloud Composer. I have tried with multiple formats for the name ( 'testingname' , "testingname" , testingname),  and it's always the same issue,

```
[2021-02-19 19:09:46,689] {taskinstance.py:671} INFO - Dependencies all met for <TaskInstance: dbt_macro.dbt_seed 2021-02-19T19:09:31.534741+00:00 [queued]>
[2021-02-19 19:09:46,803] {taskinstance.py:671} INFO - Dependencies all met for <TaskInstance: dbt_macro.dbt_seed 2021-02-19T19:09:31.534741+00:00 [queued]>
[2021-02-19 19:09:46,803] {taskinstance.py:881} INFO -
--------------------------------------------------------------------------------
[2021-02-19 19:09:46,803] {taskinstance.py:882} INFO - Starting attempt 1 of 1
[2021-02-19 19:09:46,804] {taskinstance.py:883} INFO -
--------------------------------------------------------------------------------
[2021-02-19 19:09:46,821] {taskinstance.py:902} INFO - Executing <Task(DbtSeedOperator): dbt_seed> on 2021-02-19T19:09:31.534741+00:00
[2021-02-19 19:09:46,825] {standard_task_runner.py:54} INFO - Started process 6324 to run task
[2021-02-19 19:09:46,853] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'dbt_macro', 'dbt_seed', '2021-02-19T19:09:31.534741+00:00', '--job_id', '2601', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dbt_macro.py', '--cfg_path', '/tmp/tmpefa5_hp2']
[2021-02-19 19:09:46,854] {standard_task_runner.py:78} INFO - Job 2601: Subtask dbt_seed
[2021-02-19 19:09:47,459] {logging_mixin.py:112} INFO - Running <TaskInstance: dbt_macro.dbt_seed 2021-02-19T19:09:31.534741+00:00 [running]> on host airflow-worker-54db46649-ghzgk
[2021-02-19 19:09:47,538] {dbt_hook.py:100} INFO - dbt seed --profiles-dir /home/airflow/gcs/dags/ci_profiles
[2021-02-19 19:09:47,698] {dbt_hook.py:109} INFO - Output:
[2021-02-19 19:09:49,077] {dbt_hook.py:113} INFO - Running with dbt=0.19.0
[2021-02-19 19:09:49,698] {dbt_hook.py:113} INFO - Encountered an error while reading the project:
[2021-02-19 19:09:49,698] {dbt_hook.py:113} INFO -   ERROR: Runtime Error
[2021-02-19 19:09:49,698] {dbt_hook.py:113} INFO -   at path ['name']: 'testingname' does not match '^[^\\d\\W]\\w*$'
[2021-02-19 19:09:49,698] {dbt_hook.py:113} INFO - 
[2021-02-19 19:09:49,699] {dbt_hook.py:113} INFO - Error encountered in /home/airflow/gcs/dags/dbt_project.yml
[2021-02-19 19:09:49,708] {dbt_hook.py:113} INFO - Encountered an error:
[2021-02-19 19:09:49,708] {dbt_hook.py:113} INFO - Runtime Error
[2021-02-19 19:09:49,708] {dbt_hook.py:113} INFO -   Could not run dbt
[2021-02-19 19:09:49,951] {dbt_hook.py:117} INFO - Command exited with return code 2
[2021-02-19 19:09:49,994] {taskinstance.py:1152} ERROR - dbt command failed
Traceback (most recent call last)
  File "/usr/local/lib/airflow/airflow/models/taskinstance.py", line 985, in _run_raw_tas
    result = task_copy.execute(context=context
  File "/opt/python3.6/lib/python3.6/site-packages/airflow_dbt/operators/dbt_operator.py", line 114, in execut
    self.create_hook().run_cli('seed'
  File "/opt/python3.6/lib/python3.6/site-packages/airflow_dbt/hooks/dbt_hook.py", line 121, in run_cl
    raise AirflowException("dbt command failed"
airflow.exceptions.AirflowException: dbt command faile
[2021-02-19 19:09:49,996] {taskinstance.py:1196} INFO - Marking task as FAILED. dag_id=dbt_macro, task_id=dbt_seed, execution_date=20210219T190931, start_date=20210219T190946, end_date=20210219T190949
[2021-02-19 19:09:51,332] {local_task_job.py:102} INFO - Task exited with return code 1
```

Here is a screenshot for the dependencies that have been installed in order to install dbt 0.19 on airflow 1.10.12
![image](https://user-images.githubusercontent.com/56720821/108550667-2b0db180-72ef-11eb-8b13-b0f21bf89474.png)

And the head for dbt_project.yml
```
name: testingname
version: '1.0.0'
config-version: 2
```

This shouldn't produce an error by default, locally works fine, but not on Cloud Composer.

**Comment by rkudulis** [comment]
@khaledalarja have you solved this issue? I'm facing the same error right now.
